<?php

namespace Database\Seeders;

use App\Models\Item;
use App\Models\ShopCategory;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $catId = fn(string $name) => ShopCategory::where('name', $name)->value('id');

        $items = [
            // Душевые кабины (3 товара)
            [
                'name' => 'Душевая кабина Aquanet Palau 90x90',
                'art' => 'AQ-PAL-90',
                'category' => $catId('Душевые кабины'),
                'price' => 28500,
                'priority' => 1,
                'main_item' => 1,
                'country' => 'Россия',
                'description' => 'Квадратная душевая кабина 90×90 см с поддоном, стеклянными дверями и гидромассажем.',
                'full_description' => 'Душевая кабина Aquanet Palau 90x90 — компактное и функциональное решение для ванной комнаты. Оснащена гидромассажными форсунками, тропическим душем и паровой функцией.',
            ],
            [
                'name' => 'Душевая кабина Timo Comfort T-8800',
                'art' => 'TM-8800',
                'category' => $catId('Душевые кабины'),
                'price' => 42000,
                'priority' => 2,
                'main_item' => 1,
                'country' => 'Финляндия',
                'description' => 'Прямоугольная душевая кабина 120×80 см с паровой функцией и FM-радио.',
                'full_description' => 'Timo Comfort T-8800 — душевая кабина премиум-класса с паровой функцией, гидромассажем, FM-радио и LED-подсветкой.',
            ],
            [
                'name' => 'Душевой уголок Cezares ELENA-W-AH-1',
                'art' => 'CZ-ELENA-AH',
                'category' => $catId('Душевые кабины'),
                'price' => 19800,
                'priority' => 3,
                'main_item' => 1,
                'country' => 'Италия',
                'description' => 'Душевой уголок 90×90 см с распашными дверями из закалённого стекла.',
                'full_description' => 'Душевой уголок Cezares ELENA — элегантное решение с профилем из анодированного алюминия и стеклом толщиной 6 мм.',
            ],
            // Ванны (3 товара)
            [
                'name' => 'Ванна акриловая Roca Sureste 170x70',
                'art' => 'RC-SUR-170',
                'category' => $catId('Ванны'),
                'price' => 16500,
                'priority' => 1,
                'main_item' => 1,
                'country' => 'Испания',
                'description' => 'Акриловая ванна прямоугольной формы 170×70 см.',
                'full_description' => 'Ванна Roca Sureste изготовлена из высококачественного акрила, имеет эргономичную форму и антискользящее покрытие дна.',
            ],
            [
                'name' => 'Ванна стальная Kaldewei Saniform Plus 180x80',
                'art' => 'KW-SF-180',
                'category' => $catId('Ванны'),
                'price' => 22000,
                'priority' => 2,
                'main_item' => 1,
                'country' => 'Германия',
                'description' => 'Стальная эмалированная ванна 180×80 см с покрытием Perl-Effekt.',
                'full_description' => 'Kaldewei Saniform Plus — стальная ванна с уникальным покрытием Perl-Effekt, которое отталкивает грязь и облегчает уход.',
            ],
            [
                'name' => 'Ванна чугунная Roca Malibu 170x70',
                'art' => 'RC-MAL-170',
                'category' => $catId('Ванны'),
                'price' => 58000,
                'priority' => 3,
                'main_item' => 1,
                'country' => 'Испания',
                'description' => 'Классическая чугунная ванна 170×70 см с антискользящим покрытием.',
                'full_description' => 'Чугунная ванна Roca Malibu отличается долговечностью, отличным сохранением тепла и классическим дизайном.',
            ],
            // Унитазы и биде (3 товара)
            [
                'name' => 'Унитаз подвесной Grohe Bau Ceramic',
                'art' => 'GR-BAU-C',
                'category' => $catId('Унитазы и биде'),
                'price' => 12800,
                'priority' => 1,
                'main_item' => 1,
                'country' => 'Германия',
                'description' => 'Подвесной унитаз с функцией rimless (безободковый).',
                'full_description' => 'Grohe Bau Ceramic — подвесной безободковый унитаз с покрытием PureGuard, которое препятствует образованию налёта.',
            ],
            [
                'name' => 'Унитаз напольный Cersanit Carina New Clean On',
                'art' => 'CS-CAR-CO',
                'category' => $catId('Унитазы и биде'),
                'price' => 8500,
                'priority' => 2,
                'main_item' => 1,
                'country' => 'Польша',
                'description' => 'Напольный унитаз с сиденьем Soft Close и функцией Clean On.',
                'full_description' => 'Cersanit Carina New Clean On — напольный унитаз с инновационной безободковой технологией и сиденьем с плавным закрыванием.',
            ],
            [
                'name' => 'Биде подвесное Duravit D-Code',
                'art' => 'DV-DC-B',
                'category' => $catId('Унитазы и биде'),
                'price' => 9200,
                'priority' => 3,
                'main_item' => 1,
                'country' => 'Германия',
                'description' => 'Подвесное биде в современном стиле.',
                'full_description' => 'Duravit D-Code — подвесное биде из санфарфора с глазурью WonderGliss для лёгкой очистки.',
            ],
            // Умывальники и раковины (3 товара)
            [
                'name' => 'Раковина встраиваемая Roca Gap 55',
                'art' => 'RC-GAP-55',
                'category' => $catId('Умывальники и раковины'),
                'price' => 6800,
                'priority' => 1,
                'main_item' => 1,
                'country' => 'Испания',
                'description' => 'Встраиваемая раковина 55 см из санфарфора.',
                'full_description' => 'Roca Gap 55 — встраиваемая раковина с минималистичным дизайном и покрытием Maxi Clean.',
            ],
            [
                'name' => 'Умывальник на пьедестале Cersanit Carina 65',
                'art' => 'CS-CAR-65',
                'category' => $catId('Умывальники и раковины'),
                'price' => 7400,
                'priority' => 2,
                'main_item' => 1,
                'country' => 'Польша',
                'description' => 'Умывальник на пьедестале 65 см, классический стиль.',
                'full_description' => 'Cersanit Carina 65 — умывальник на пьедестале из высококачественного санфарфора с тремя отверстиями под смеситель.',
            ],
            [
                'name' => 'Раковина накладная Duravit Starck 1 60',
                'art' => 'DV-ST1-60',
                'category' => $catId('Умывальники и раковины'),
                'price' => 14500,
                'priority' => 3,
                'main_item' => 1,
                'country' => 'Германия',
                'description' => 'Накладная раковина 60 см дизайна Philippe Starck.',
                'full_description' => 'Duravit Starck 1 — накладная раковина с покрытием WonderGliss и авторским дизайном Philippe Starck.',
            ],
            // Смесители (3 товара)
            [
                'name' => 'Смеситель для ванны Grohe Eurostyle 33591',
                'art' => 'GR-ES-33591',
                'category' => $catId('Смесители'),
                'price' => 5600,
                'priority' => 1,
                'main_item' => 1,
                'country' => 'Германия',
                'description' => 'Однорычажный смеситель для ванны с душевым гарнитуром.',
                'full_description' => 'Grohe Eurostyle 33591 — смеситель с технологией EcoJoy для экономии воды и картриджем SilkMove.',
            ],
            [
                'name' => 'Смеситель для кухни Hansgrohe Talis S 72800',
                'art' => 'HG-TS-72800',
                'category' => $catId('Смесители'),
                'price' => 8900,
                'priority' => 2,
                'main_item' => 1,
                'country' => 'Германия',
                'description' => 'Однорычажный кухонный смеситель с поворотным изливом.',
                'full_description' => 'Hansgrohe Talis S — кухонный смеситель с технологией ComfortZone и покрытием хром.',
            ],
            [
                'name' => 'Термостат для душа Hansgrohe ShowerTablet 600',
                'art' => 'HG-ST-600',
                'category' => $catId('Смесители'),
                'price' => 24500,
                'priority' => 3,
                'main_item' => 1,
                'country' => 'Германия',
                'description' => 'Термостатический смеситель для душа с двумя выходами.',
                'full_description' => 'Hansgrohe ShowerTablet 600 — термостат с технологией SafetyStop и точной регулировкой температуры.',
            ],
            // Радиаторы отопления (3 товара)
            [
                'name' => 'Радиатор биметаллический Rifar Base 500 10 секций',
                'art' => 'RF-B500-10',
                'category' => $catId('Радиаторы отопления'),
                'price' => 7200,
                'priority' => 1,
                'main_item' => 1,
                'country' => 'Россия',
                'description' => 'Биметаллический радиатор 500 мм, 10 секций, мощность 2040 Вт.',
                'full_description' => 'Rifar Base 500 — биметаллический радиатор с рабочим давлением 20 бар и антикоррозийным покрытием.',
            ],
            [
                'name' => 'Радиатор алюминиевый Global ISEO 500 8 секций',
                'art' => 'GL-IS-500-8',
                'category' => $catId('Радиаторы отопления'),
                'price' => 4800,
                'priority' => 2,
                'main_item' => 1,
                'country' => 'Италия',
                'description' => 'Алюминиевый радиатор 500 мм, 8 секций, мощность 1368 Вт.',
                'full_description' => 'Global ISEO 500 — алюминиевый радиатор итальянского производства с высокой теплоотдачей.',
            ],
            [
                'name' => 'Радиатор стальной Kermi FKO 22 500x1000',
                'art' => 'KM-FKO-22',
                'category' => $catId('Радиаторы отопления'),
                'price' => 9600,
                'priority' => 3,
                'main_item' => 1,
                'country' => 'Германия',
                'description' => 'Стальной панельный радиатор тип 22, 500×1000 мм, мощность 1644 Вт.',
                'full_description' => 'Kermi FKO 22 — стальной радиатор с боковым подключением и встроенным термоклапаном.',
            ],
            // Котлы отопления (3 товара)
            [
                'name' => 'Котёл газовый Baxi LUNA-3 240i',
                'art' => 'BX-L3-240',
                'category' => $catId('Котлы отопления'),
                'price' => 52000,
                'priority' => 1,
                'main_item' => 1,
                'country' => 'Италия',
                'description' => 'Двухконтурный настенный газовый котёл 24 кВт.',
                'full_description' => 'Baxi LUNA-3 240i — двухконтурный котёл с закрытой камерой сгорания, КПД 92%, встроенным расширительным баком.',
            ],
            [
                'name' => 'Котёл электрический Protherm Скат 9K',
                'art' => 'PT-SK-9K',
                'category' => $catId('Котлы отопления'),
                'price' => 28000,
                'priority' => 2,
                'main_item' => 1,
                'country' => 'Словакия',
                'description' => 'Электрический котёл 9 кВт для отопления площади до 90 м².',
                'full_description' => 'Protherm Скат 9K — электрический котёл с плавной регулировкой мощности и встроенным насосом.',
            ],
            [
                'name' => 'Котёл твердотопливный Buderus Logano G221-25',
                'art' => 'BD-G221-25',
                'category' => $catId('Котлы отопления'),
                'price' => 89000,
                'priority' => 3,
                'main_item' => 1,
                'country' => 'Германия',
                'description' => 'Твердотопливный котёл 25 кВт на дровах и угле.',
                'full_description' => 'Buderus Logano G221-25 — чугунный твердотопливный котёл с КПД 89% и большой топкой.',
            ],
            // Водонагреватели (3 товара)
            [
                'name' => 'Водонагреватель накопительный Ariston ABS PRO R 80V',
                'art' => 'AR-PR-80V',
                'category' => $catId('Водонагреватели'),
                'price' => 14500,
                'priority' => 1,
                'main_item' => 1,
                'country' => 'Италия',
                'description' => 'Накопительный водонагреватель 80 л, вертикальный.',
                'full_description' => 'Ariston ABS PRO R 80V — водонагреватель с эмалевым покрытием бака и магниевым анодом для защиты от коррозии.',
            ],
            [
                'name' => 'Водонагреватель проточный Bosch Tronic 3000 U',
                'art' => 'BS-TR-3000',
                'category' => $catId('Водонагреватели'),
                'price' => 3800,
                'priority' => 2,
                'main_item' => 1,
                'country' => 'Германия',
                'description' => 'Проточный электрический водонагреватель 6 кВт.',
                'full_description' => 'Bosch Tronic 3000 U — компактный проточный водонагреватель с электронным управлением и защитой от перегрева.',
            ],
            [
                'name' => 'Водонагреватель накопительный Thermex IF 100V',
                'art' => 'TX-IF-100V',
                'category' => $catId('Водонагреватели'),
                'price' => 18200,
                'priority' => 3,
                'main_item' => 1,
                'country' => 'Россия',
                'description' => 'Накопительный водонагреватель 100 л с сухим ТЭНом.',
                'full_description' => 'Thermex IF 100V — водонагреватель с двумя сухими ТЭНами, не контактирующими с водой, что увеличивает срок службы.',
            ],
            // Трубы и фитинги (3 товара)
            [
                'name' => 'Труба полипропиленовая Ekoplastik PN20 32мм (2м)',
                'art' => 'EK-PP-32',
                'category' => $catId('Трубы и фитинги'),
                'price' => 320,
                'priority' => 1,
                'main_item' => 1,
                'country' => 'Чехия',
                'description' => 'Полипропиленовая труба армированная стекловолокном, PN20, диаметр 32 мм.',
                'full_description' => 'Ekoplastik PN20 — труба для горячего и холодного водоснабжения, армированная стекловолокном для снижения теплового расширения.',
            ],
            [
                'name' => 'Труба металлопластиковая Valtec 16x2 (50м)',
                'art' => 'VT-MP-16',
                'category' => $catId('Трубы и фитинги'),
                'price' => 4200,
                'priority' => 2,
                'main_item' => 1,
                'country' => 'Россия',
                'description' => 'Металлопластиковая труба 16×2 мм, бухта 50 м.',
                'full_description' => 'Valtec 16x2 — металлопластиковая труба для систем отопления и водоснабжения с рабочим давлением 10 бар.',
            ],
            [
                'name' => 'Фитинг полипропиленовый угол 90° Ekoplastik 32мм',
                'art' => 'EK-FT-90-32',
                'category' => $catId('Трубы и фитинги'),
                'price' => 85,
                'priority' => 3,
                'main_item' => 1,
                'country' => 'Чехия',
                'description' => 'Полипропиленовый угол 90° для труб диаметром 32 мм.',
                'full_description' => 'Ekoplastik угол 90° — фитинг из полипропилена для монтажа систем водоснабжения и отопления.',
            ],
            // Насосы и насосные станции (3 товара)
            [
                'name' => 'Насос циркуляционный Grundfos UPS 25-60',
                'art' => 'GF-UPS-2560',
                'category' => $catId('Насосы и насосные станции'),
                'price' => 8900,
                'priority' => 1,
                'main_item' => 1,
                'country' => 'Дания',
                'description' => 'Циркуляционный насос для систем отопления, 3 скорости.',
                'full_description' => 'Grundfos UPS 25-60 — надёжный циркуляционный насос с мокрым ротором для систем отопления и ГВС.',
            ],
            [
                'name' => 'Насосная станция Джилекс Джамбо 70/50 Н-24',
                'art' => 'JL-JB-7050',
                'category' => $catId('Насосы и насосные станции'),
                'price' => 12500,
                'priority' => 2,
                'main_item' => 1,
                'country' => 'Россия',
                'description' => 'Насосная станция с гидроаккумулятором 24 л, производительность 70 л/мин.',
                'full_description' => 'Джилекс Джамбо 70/50 Н-24 — насосная станция для автономного водоснабжения с реле давления и манометром.',
            ],
            [
                'name' => 'Насос дренажный Grundfos Unilift CC 7 A1',
                'art' => 'GF-CC7-A1',
                'category' => $catId('Насосы и насосные станции'),
                'price' => 6800,
                'priority' => 3,
                'main_item' => 1,
                'country' => 'Дания',
                'description' => 'Дренажный насос для откачки чистой и слабозагрязнённой воды.',
                'full_description' => 'Grundfos Unilift CC 7 A1 — дренажный насос с поплавковым выключателем и производительностью 7 м³/ч.',
            ],
        ];

        foreach ($items as $data) {
            $data['meta_title'] = $data['meta_title'] ?? $data['name'];
            $data['meta_description'] = $data['meta_description'] ?? $data['description'];
            Item::firstOrCreate(['art' => $data['art']], $data);
        }
    }
}
